name = "EnzymeFitting"
uuid = "bf31c7e1-2152-4d3a-bc7a-576095d562b2"
authors = ["Denis Titov titov@berkeley.edu and contributors"]
version = "1.0.0-DEV"

[deps]
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"


[targets]
test = ["Test", "SafeTestsets", "BenchmarkTools", "CSV"]
